language: python

python:
  - 2.5
  - 2.6
  - 2.7
  - pypy

before_install: pip install --use-mirrors Django djangotestxmlrpc
install: python setup.py install
script: python test_environment/manage.py test
